name: Bearer Scanner

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read # Minimal permissions

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Run Bearer
        uses: bearer/actions@v2
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
